CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
ITEM_TOKEN_INDEX = -201
DEFAULT_ITEM_TOKEN = "<item>"
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"

MODAL_TOKENS = {
    'vision': DEFAULT_IMAGE_TOKEN,
    'item': DEFAULT_ITEM_TOKEN
}
MODAL_TOKEN_INDEXES = {
    'vision': IMAGE_TOKEN_INDEX,
    'item': ITEM_TOKEN_INDEX
}
MODAL_TOKEN_MAPPING = {MODAL_TOKENS[k]: MODAL_TOKEN_INDEXES[k] for k in MODAL_TOKENS}